### ISSUE TITLE
Spoilers

### ISSUE THREAD

**Issue by Antiik91** [saskeli/ohtu-viikko1#1]
much?

**Comment by saskeli** [comment]
The movie is ancient. DEAL WITH IT!

**Comment by Antiik91** [comment]
:(

**Comment by saskeli** [comment]
LOPETA!

**Comment by Antiik91** [comment]
Mä YRITÄN

la 18. maaliskuuta 2017 klo 16.34 saskeli <notifications@github.com>
kirjoitti:
